[package]
name = "xlran"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.6.4"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.25.0" }

[[target.starknet-contract]]
casm = true
sierra = true

[scripts]
test = "snforge test"